import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('http://localhost:3000/');
    await page.getByRole('link', { name: '🏠 Aquariums View and manage' }).click();
    await page.getByRole('button', { name: 'Switch to English' }).click();
    await page.getByRole('button', { name: 'Przełącz na polski' }).click();
    await page.getByRole('button', { name: 'Switch to English' }).click();
    await page.getByText('📊Statistics').click();
    await page.getByRole('button', { name: 'Close' }).click();
    await page.getByText('📋').click();
    await page.getByText('All Actions').click();
    await page.getByRole('option', { name: 'Created' }).click();
    await page.getByText('Created').click();
    await page.getByRole('option', { name: 'Plant Removed' }).click();
    await page.getByText('All Aquariums').click();
    await page.locator('.MuiBackdrop-root.MuiBackdrop-invisible').click();
    await page.getByText('Newest First').click();
    await page.getByRole('option', { name: 'Oldest First' }).click();
    await page.getByText('Plant Removed').click();
    await page.getByRole('option', { name: 'Edited' }).click();
    await page.getByText('Edited').click();
    await page.getByRole('option', { name: 'Deleted' }).click();
    await page.getByText('Deleted').click();
    await page.getByRole('option', { name: 'Fish Added' }).click();
    await page.getByText('Fish Added').click();
    await page.getByRole('option', { name: 'Fish Removed' }).click();
    await page.getByText('Fish Removed').click();
    await page.getByRole('option', { name: 'Plant Added' }).click();
    await page.getByText('Plant Added').click();
    await page.getByRole('option', { name: 'Plant Removed' }).click();
    await page.getByText('Plant Removed').click();
    await page.getByRole('option', { name: 'Parameter Changed' }).click();
    await page.getByRole('button', { name: 'Close' }).click();
    await page.getByRole('button', { name: 'Invite Friend' }).click();
    await page.getByRole('heading', { name: 'Contacts List' }).click();
    await page.getByText('Nie można załadować danych uż').nth(1).click();
    await page.getByRole('alert').first().click();
    await page.getByText('Invite to collaborationNie mo').click();
    await page.getByRole('button', { name: 'Create Aquarium' }).click();
    await page.getByRole('textbox', { name: 'Aquarium Name' }).click();
    await page.getByRole('textbox', { name: 'Aquarium Name' }).press('CapsLock');
    await page.getByRole('textbox', { name: 'Aquarium Name' }).fill('TEST');
    await page.getByText('Freshwater').click();
    await page.getByRole('option', { name: 'Saltwater' }).click();
    await page.getByRole('spinbutton', { name: 'Water Temperature (°C)' }).fill('29');
    await page.getByRole('spinbutton', { name: 'pH' }).click();
    await page.getByRole('spinbutton', { name: 'pH' }).press('Enter');
    await page.getByRole('spinbutton', { name: 'pH' }).fill('8.4');
    await page.getByRole('spinbutton', { name: 'Water Hardness (dGH)' }).click();
    await page.getByRole('spinbutton', { name: 'Water Hardness (dGH)' }).fill('2');
    await page.getByRole('textbox', { name: 'Aquarium Description' }).click();
    await page.getByRole('textbox', { name: 'Aquarium Description' }).fill('test');
    await page.getByRole('button', { name: 'Create' }).click();

});