name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test tests/Unit_tests
        continue-on-error: true   
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm install

      - name: Run Integration Tests
        run: npm test tests/Integration_tests
        continue-on-error: true   